apiVersion: v1
kind: DeploymentConfig
metadata:
  name: sonarqube-postgres
  labels:
    name: sonarqube-postgres
    app: sonarqube
spec:
  strategy:
    type: Rolling
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - sonarqube-postgres
        from:
          kind: ImageStreamTag
          namespace: wei-sandbox
          name: postgres:10.4
  replicas: 1
  selector:
    name: sonarqube-postgres
    app: sonarqube
  template:
    metadata:
      name: sonarqube-postgres
      labels:
        name: sonarqube-postgres
        app: sonarqube
    spec:
      containers:
        - name: sonarqube-postgres
          image: ""
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
          resources:
            requests:
              memory: "1200Mi"
              cpu: .10
            limits:
              memory: "2500Mi"
              cpu: .50
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim